version: "3"

services:
  # Service that will run node
  node:
    # Base image of the container
    image: node:16.14
    # Container name to facilitate execution
    container_name: store_manager
    # Same as `docker run -t`
    tty: true
    # Same as `docker run -i`
    stdin_open: true
    # Replaces the default command of the node image
    command: bash # you can replace `bash` with `npm run debug` to start the API when the container is started  
    # Restarts the image if something makes it stop
    restart: always
    # Default execution directory
    working_dir: /home/node/app
    # List of volumes (directories) mapped from outside to inside the container
    volumes:
      # Mounts the current directory, with all project data, 
      # inside the /app directory
      - ./:/home/node/app
    # List of services on which this service depends
    depends_on:
      # Needs the database running before bringing up the node
      - db
    # List of ports mapped from inside to outside the container
    # in the notation outside_port:inside_port
    ports:
      # Exposes the default application port: change here if you use another port
      - 3000:3000
      - 9229:9229
    # Configures the environment variables inside the container
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: db # Name of the service just below
      PORT: '3000'
      HOST: store_manager
    networks:
      # Connects this service with the network that was created
      - store_manager_net

  # Service that will run the database
  db:
    container_name: store_manager_db
    image: mysql:8.0.23
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # Ensure that there will be no port conflicts with a database that is
      # running locally
      - 3306:3306
    networks:
      # Connects this service with the network that was created 
      - store_manager_net

# List of networks that the containers will use
networks:
  # Creates the network that connects the `db` and `node` services 
  store_manager_net:
    # Specifies the network driver
    driver: bridge

# The `tty`, `stdin_open` and `command` keys make the container keep
# running in the background, as well as make it possible to use the command
# `docker attach`, already attaching the current terminal to the container, directly
# in bash. Despite this, using attach more than once will replicate the
# terminal, so it is better to use the `docker exec` command.

# The renaming of the default network is done because otherwise the name of the network will be
# the name of the directory where the current file is located, which can make it difficult
# to list individually.